from __future__ import annotations

from application.services.auto_label_service import AutoLabelService
from application.services.convert_service import ConvertService
from application.services.split_service import SplitService
from application.services.stats_service import StatsService
